# Generated by Django 3.2.6 on 2021-08-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('node_id', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('application_id', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('round_failure_avg', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('status', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=200)),
                ('uptime', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('application_url', models.CharField(max_length=200)),
            ],
        ),
    ]
