# Generated by Django 3.2.6 on 2021-08-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
        ('nodeinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinfo',
            name='subscribed_users',
            field=models.ManyToManyField(related_name='subscribed_users', to='tgbot.User'),
        ),
    ]
