# Generated by Django 3.2.6 on 2021-08-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
        ('nodeinfo', '0002_nodeinfo_subscribed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinfo',
            name='network',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='nodeinfo',
            name='subscribed_users',
            field=models.ManyToManyField(related_name='subscribed_nodes', to='tgbot.User'),
        ),
    ]
